### PR TITLE
chore(lib): release @storyblok/field-plugin@1.4.2

### PR DESCRIPTION
**Pull request by ECJ222**
## What?

This PR updates the lib version for release.

### CODE REVIEW

**Review by Dawntraoz — APPROVED** [review]
LGTM!

**Review by demetriusfeijoo — APPROVED** [review]
Let's GOO 🚀 🚀 
If you need any help with the next steps necessary to release a new version, just let me know @ECJ222. 🙏

**Comment by ECJ222** [comment]
Thanks man @demetriusfeijoo!

**Comment by demetriusfeijoo** [comment]
@all-contributors please add @ECJ222 for code.

**Pull request merged**
