### PR TITLE
chore(lib): release @storyblok/field-plugin@1.4.0

### PR DESCRIPTION
**Pull request by BibiSebi**
## What?

This PR updates the lib version for release.

### CODE REVIEW

**Review by demetriusfeijoo — APPROVED** [review]
The SDK itself has nothing new to be released, I guess, but releasing it is necessary so we can keep the CLI and SDK in the same version, right? 🤔 

I don't release nothing for too long that I can't recall 🤣

**Comment by BibiSebi** [comment]
Indeed those were my thoughts. But maybe it's fine to have different versions.

**Comment by BibiSebi** [comment]
@demetriusfeijoo let me close it, from the history it seems fine as well, so i will only open the PR for CLI.

**Comment by demetriusfeijoo** [comment]
okidoki @BibiSebi. 🙏 
I found a thread about which path we should choose and it was about releasing only the package that had the change, indeed. 🙌

**Pull request closed without merging**
