### PR TITLE
chore(common): update pull-request title checking logic

### PR DESCRIPTION
**Pull request by eunjae-lee**
## What?

This PR updates pull-request title checking logic.

Now it's following the semantic rules: https://github.com/amannn/action-semantic-pull-request

## Why?

EXT-1255

It helps us better distinguish commits by type of work and package.

## Discussion

Current I've put the following scopes:

- common
- lib
- sandbox
- cli
- cli-create
- cli-add
- cli-deploy

Any update you'd like to see?

(They are used like `fix(cli-deploy): load environment variables from .env.local`)

### CODE REVIEW

**Review by johannes-lindgren — APPROVED** [review]
Does a change to the template fall under the scope `cli-create`?

**Comment by eunjae-lee** [comment]
> Does a change to the template fall under the scope `cli-create`?

Good point. I think we should have a separate scope `template`. What do you think?

I also think it's a bit too much to have `cli-xyz` scopes. We could have `cli` scope only. What do you think about this?

**Review by BibiSebi — APPROVED** [review]
💯

**Comment by eunjae-lee** [comment]
final scopes:

- common
- lib
- sandbox
- cli
- template

**Pull request merged**
