### PR TITLE
fix(cli): fix tilde issue with create command

### PR DESCRIPTION
**Pull request by eunjae-lee**
## What?

If you run the following, it should work:

```
npx @storyblok/field-plugin-cli@beta create --dir=~/sandbox
```

However, the tilde(`~`) in ~/sandbox doesn’t get expanded correctly, and it actually creates a folder like the following:

```
current directory
  ㄴ ~
    ㄴ sandbox
```

So this should be fixed.

## Why?

JIRA: EXT-1862

### CODE REVIEW

**Comment by eunjae-lee** [comment]
Current dependencies on/for this PR:
* main
  * **PR #231** <a href="https://app.graphite.dev/github/pr/storyblok/field-plugin/231" target="_blank">Graphite</a> 
    * **PR #233** <a href="https://app.graphite.dev/github/pr/storyblok/field-plugin/233" target="_blank">Graphite</a> 
      * **PR #234** <a href="https://app.graphite.dev/github/pr/storyblok/field-plugin/234" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/storyblok/field-plugin/234?utm_source=stack-comment).

**Review by BibiSebi — APPROVED** [review]
💯

**Comment by eunjae-lee** [comment]
@eunjae-lee started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/storyblok/field-plugin/234).

**Comment by eunjae-lee** [comment]
@eunjae-lee merged this pull request with [Graphite](https://app.graphite.dev/github/pr/storyblok/field-plugin/234).

**Pull request merged**
