### PR TITLE
fix(template): revert changes to templates

### PR DESCRIPTION
**Pull request by johannes-lindgren**
## What?

Revert changes to templates that introduced enablePortalModal
## Why?

To make the CI pass to publish the library, we need to be able to build the templates, but the templates are using the old version

The solution is to

1. revert the changes to the templates (this PR)
2. Publish the library
3. Add the changes back again
4. Publish the CLI

### CODE REVIEW

**Review by demetriusfeijoo — DISMISSED** [review]
Hey @johannes-lindgren 👋 

I think we can fix the CI so it won't happen again for future releases.

I opened this PR [here](https://github.com/storyblok/field-plugin/pull/428) with a fix.
Let me know what you think.

**Comment by johannes-lindgren** [comment]
> Hey @johannes-lindgren 👋
> 
> I think we can fix the CI so it won't happen again for future releases.
> 
> I opened this PR [here](https://github.com/storyblok/field-plugin/pull/428) with a fix. Let me know what you think.

But is this PR fine? Or what should I change?

I approved your PR

**Comment by demetriusfeijoo** [comment]
Hey @johannes-lindgren 👋 
The PR is fine but not need to do it anymore. 

Once a [fix](https://github.com/storyblok/field-plugin/pull/428) was applied to the CI, you could just re-open [this release PR](https://github.com/storyblok/field-plugin/pull/425) without the need to revert your changes as done here. 🤔

**Comment by johannes-lindgren** [comment]
This fixes it: https://github.com/storyblok/field-plugin/pull/428

**Comment by johannes-lindgren** [comment]
@Dawntraoz pointed out another failing job: https://github.com/storyblok/field-plugin/actions/runs/11385607709/job/31677571828?pr=425

So it seems that the steps outlined in PR might be the best course of action after all.

Cc: @demetriusfeijoo

**Review by Dawntraoz — APPROVED** [review]
LGTM!

**Comment by demetriusfeijoo** [comment]
Hey @johannes-lindgren 👋 

I didn't get the reason to open this PR again once the changes were already [merged](https://github.com/storyblok/field-plugin/pull/425) 🤔 

Now, the next step would be to also publish the CLI and then run the actions responsible for pushing a new package to NPM for both the CLI and Library.

But please, let me know if you need any help with that 🙌

**Comment by johannes-lindgren** [comment]
The point is to always keep main in a state that is releasable

**Comment by demetriusfeijoo** [comment]
Yeah, we may think about using some publishing/versioning tool, such as Changesets to streamline the process. 🤔

**Pull request closed without merging**
